# Generated by Django 5.1.3 on 2025-07-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student/Parent'), ('tutor', 'Tutor')], default='student', max_length=10),
        ),
    ]
